# Generated by Django 4.0.4 on 2022-05-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_attendance_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-id"]},
        ),
    ]
