# Generated by Django 3.2.8 on 2021-10-28 00:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_workshop"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="transpired_at",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
