# Generated by Django 3.2.8 on 2021-10-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_workshop_transpired_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=300, verbose_name="Title of your workshop"
                    ),
                ),
                (
                    "topic",
                    models.TextField(
                        blank=True, null=True, verbose_name="What is it about?"
                    ),
                ),
                (
                    "audience",
                    models.TextField(
                        blank=True, null=True, verbose_name="Who is it for?"
                    ),
                ),
                (
                    "outcome",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="What will the attendees have learned at the end of your workshop?",
                    ),
                ),
                (
                    "when",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="When approximately are you thinking of presenting this?",
                    ),
                ),
            ],
        ),
    ]
