# Generated by Django 3.2.8 on 2021-10-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="email",
            field=models.EmailField(
                default="submitter@chaitinschool.org",
                max_length=254,
                verbose_name="What's your email?",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="submission",
            name="links",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Any of website, blog, twitter, github",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="submitter",
            field=models.CharField(
                default="Ran Dom", max_length=300, verbose_name="What's your name?"
            ),
            preserve_default=False,
        ),
    ]
