# Generated by Django 4.1 on 2022-09-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_post_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("slug", models.CharField(max_length=300, unique=True)),
                ("data", models.BinaryField()),
                ("extension", models.CharField(max_length=10)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
