# Generated by Django 4.1 on 2022-09-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorship",
            name="is_available",
            field=models.BooleanField(default=False),
        ),
    ]
