# Generated by Django 4.1.1 on 2022-11-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_delete_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="is_confirmed",
            field=models.BooleanField(default=True),
        ),
    ]
