# Generated by Django 3.2.8 on 2021-10-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_auto_20211028_0139"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="byline",
            field=models.CharField(default="Chaitin School", max_length=300),
            preserve_default=False,
        ),
    ]
