# Generated by Django 3.2.8 on 2021-11-11 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_post_byline"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Request",
            new_name="Proposal",
        ),
    ]
