# Generated by Django 4.1.1 on 2022-11-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_workshop_is_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshop",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
