# Generated by Django 3.2.8 on 2021-11-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_rename_request_proposal"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="location",
            field=models.CharField(default="default location", max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workshop",
            name="location_url",
            field=models.URLField(default="http://default.location/"),
            preserve_default=False,
        ),
    ]
