# Generated by Django 4.2.5 on 2023-11-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_alter_workshop_is_confirmed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("happened_at", models.DateField()),
                ("text", models.TextField()),
            ],
        ),
    ]
