# Generated by Django 4.2.7 on 2023-11-08 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_incident"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="published_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
