# Generated by Django 3.2.8 on 2021-11-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_auto_20211116_2243"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshop",
            name="transpired_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
