# Generated by Django 5.0.1 on 2024-01-08 20:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_incident_published_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar_data",
        ),
        migrations.RemoveField(
            model_name="user",
            name="avatar_ext",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_public",
        ),
    ]
