# Generated by Django 4.0 on 2022-02-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_emailrecord"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workshop",
            old_name="transpired_at",
            new_name="scheduled_at",
        ),
    ]
