# Generated by Django 5.0.1 on 2024-01-08 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_remove_user_avatar_data_remove_user_avatar_ext_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="full_name",
        ),
    ]
