# Generated by Django 5.0.1 on 2024-01-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_remove_user_full_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="about",
        ),
        migrations.AddField(
            model_name="user",
            name="plan",
            field=models.TextField(blank=True),
        ),
    ]
