# Generated by Django 4.0 on 2022-02-11 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_workshop_scheduled_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workshop",
            old_name="location",
            new_name="location_name",
        ),
    ]
