# Generated by Django 4.0 on 2022-02-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_rename_location_workshop_location_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="location_address",
            field=models.CharField(default="London", max_length=300),
            preserve_default=False,
        ),
    ]
