# Generated by Django 4.0 on 2022-02-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_workshop_location_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
            ],
        ),
    ]
