# Generated by Django 4.0 on 2022-03-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
