# Generated by Django 4.0 on 2022-04-02 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="workshop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.workshop"
            ),
        ),
    ]
