# Generated by Django 4.0 on 2022-04-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_alter_attendance_workshop"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("workshop", "email")},
        ),
    ]
