# Generated by Django 4.0 on 2022-04-18 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_alter_attendance_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workshop",
            options={"ordering": ["-scheduled_at"]},
        ),
    ]
